### ISSUE TITLE
meteor-apollo-accounts package development

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/meteor-apollo-accounts-example#3]
@nicolaslopezj short question: What is your setup to develop the npm and the Meteor package?
If possible I would like to test them with my example app, while using your git repository as source for the packages. Do you have a Setup that works like this?

**Comment by nicolaslopezj** [comment]
For the server part it would be very easy, just set the env var METEOR_PACKAGE_DIRS to the path containing the accounts package. Changes will make the app refresh

For the client it would be more difficult in this case (client meteor app). You need to "npm link" the package and run "npm run watch" in the accounts package folder to re-compile the package when there are changes. To view changes you must change a file because meteor doesn't watch node_modules.

**Comment by janikvonrotz** [comment]
npm link worked well. 

But it did not work for the Meteor package. I've updated the env variable, but it does not load the package from the directory.

```
PS C:\LocalDrive\GitHub\meteor-apollo-accounts-example> $env:METEOR_PACKAGE_DIRS
C:\LocalDrive\GitHub\meteor-apollo-accounts

PS C:\LocalDrive\GitHub\meteor-apollo-accounts-example> meteor add nicolaslopezj:apollo-accounts

Changes to your project's package version selections:

nicolaslopezj:apollo-accounts  added, version 1.3.7

nicolaslopezj:apollo-accounts: Meteor accounts in GraphQL
```

Do I have to set a different path? Or do I have to install the package differently?

**Comment by nicolaslopezj** [comment]
Check here https://guide.meteor.com/writing-atmosphere-packages.html#overriding-atmosphere-packages

**Comment by janikvonrotz** [comment]
Solved it. It seems windows still uses the PACKAGE_DIRS var instead of the METEOR_PACKAGE_DIRS var.
